import React from 'react';
import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import EquipmentServicePanel from './EquipmentServicePanel';
import type { Equipment } from '@/types';
const writes=vi.hoisted(()=>({saveEquipmentMaintenanceRules:vi.fn(),recordEquipmentHours:vi.fn(),recordEquipmentService:vi.fn()}));
vi.mock('@/lib/db',()=>({dbService:writes}));
const equipment: Equipment={id:'e',name:'Washer',category:'equipment',status:'working',operatingHours:120, carsUsed:400,maintenanceRules:[{id:'pump',title:'Pump service',intervalHours:100,intervalMonths:6,source:'Manual section 4; standard use',confirmed:true,baselineHours:50,baselineDate:'2026-06-01'}]};
(globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
let root: ReturnType<typeof createRoot>;
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-10-08T12:00:00Z'));Object.values(writes).forEach(x=>x.mockReset().mockResolvedValue(undefined));});
afterEach(async()=>{if(root) await act(async()=>root.unmount());document.body.innerHTML='';vi.useRealTimers();});
async function render(demo=true,changed=vi.fn(),saved=vi.fn()){const el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root.render(<EquipmentServicePanel items={[equipment]} demo={demo} actor={{id:'boss',name:'Manager'}} onSampleChange={changed} onSaved={saved}/>));return el;}
async function click(el:HTMLElement,text:string){const b=Array.from(el.querySelectorAll('button')).find(x=>x.textContent===text);expect(b).toBeDefined();await act(async()=>b!.click());}
async function input(el:HTMLElement,label:string,value:string){const node=Array.from(el.querySelectorAll('input,select')).find(x=>x.getAttribute('aria-label')===label) as HTMLInputElement;expect(node).toBeDefined();await act(async()=>{const set=Object.getOwnPropertyDescriptor(node.tagName==='SELECT'?HTMLSelectElement.prototype:HTMLInputElement.prototype,'value')!.set!;set.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));node.dispatchEvent(new Event('change',{bubbles:true}));});}
it('requires a fresh measured value and isolates sample hour saves from live writes and replacement usage',async()=>{const changed=vi.fn();const el=await render(true,changed);await click(el,'Save measured hours');expect(changed).not.toHaveBeenCalled();await input(el,'Measured operating hours','120.5');await click(el,'Save measured hours');expect(changed.mock.calls[0][0]).toMatchObject({operatingHours:120.5,carsUsed:400,hoursReadings:[{hours:120.5,recordedBy:'boss'}]});Object.values(writes).forEach(x=>expect(x).not.toHaveBeenCalled());expect(el.textContent).toContain('150');});
it.each(['119','Infinity','-1'])('rejects invalid or decreasing measured hours %s',async value=>{const changed=vi.fn();const el=await render(true,changed);await input(el,'Measured operating hours',value);await click(el,'Save measured hours');expect(changed).not.toHaveBeenCalled();expect(el.querySelector('[role="alert"]')).not.toBeNull();});
it('awaits remote success, reports failure and retains input without sample mutation',async()=>{writes.recordEquipmentHours.mockRejectedValue(new Error('Network failed; check history before retry'));const changed=vi.fn(),saved=vi.fn();const el=await render(false,changed,saved);await input(el,'Measured operating hours','121');await click(el,'Save measured hours');expect(el.querySelector('[role="alert"]')?.textContent).toContain('Network failed');expect(changed).not.toHaveBeenCalled();expect(saved).not.toHaveBeenCalled();expect((el.querySelector('[aria-label="Measured operating hours"]') as HTMLInputElement).value).toBe('121');});
it('saves an incomplete unconfirmed source draft and explains missing baseline',async()=>{const changed=vi.fn();const el=await render(true,changed);await click(el,'Add service rule');await input(el,'Rule title','Filter');await click(el,'Save rule draft');expect(changed.mock.calls[0][0].maintenanceRules[1]).toMatchObject({title:'Filter',confirmed:false,source:''});expect(el.textContent).toContain('unknown');});
it('records only completed services against their independent rule and displays history',async()=>{const changed=vi.fn();const el=await render(true,changed);await click(el,'Record completed service');await input(el,'Service measured hours','120');await click(el,'Save completed service');const item=changed.mock.calls[0][0];expect(item.serviceHistory[0]).toMatchObject({ruleId:'pump',hours:120,recordedBy:'boss',date:'2026-10-08'});expect(item.carsUsed).toBe(400);expect(el.textContent).toContain('Completed service history');expect(el.textContent).toContain('120 hours');});
it('requires a source before confirming and revokes confirmation after source edits',async()=>{const changed=vi.fn();const el=await render(true,changed);await click(el,'Add service rule');await input(el,'Rule title','Filter');await input(el,'Rule interval hours','100');const check=el.querySelector('input[type="checkbox"]') as HTMLInputElement;await act(async()=>check.click());await click(el,'Save verified rule');expect(changed).not.toHaveBeenCalled();expect(el.querySelector('[role="alert"]')?.textContent).toContain('source');await input(el,'Rule source','Manual 4, ordinary usage');expect(check.checked).toBe(false);await click(el,'Save rule draft');expect(changed.mock.calls[0][0].maintenanceRules[1]).toMatchObject({confirmed:false,source:'Manual 4, ordinary usage',intervalHours:100});});
it('rejects missing service hours for an hours rule and handles live service failures',async()=>{const changed=vi.fn(),saved=vi.fn();const el=await render(false,changed,saved);await click(el,'Record completed service');await click(el,'Save completed service');expect(writes.recordEquipmentService).not.toHaveBeenCalled();expect(el.querySelector('[role="alert"]')?.textContent).toContain('measured service hours');await input(el,'Service measured hours','121');await click(el,'Save completed service');expect(writes.recordEquipmentService).not.toHaveBeenCalled();await input(el,'Service measured hours','120');writes.recordEquipmentService.mockRejectedValue(new Error('Service connection failed'));await click(el,'Save completed service');expect(el.querySelector('[role="alert"]')?.textContent).toContain('Service connection failed');expect(changed).not.toHaveBeenCalled();expect(saved).not.toHaveBeenCalled();});
it('notifies live refresh only after a successful awaited hours save',async()=>{let resolve!:()=>void;writes.recordEquipmentHours.mockImplementation(()=>new Promise<void>(done=>{resolve=done;}));const changed=vi.fn(),saved=vi.fn();const el=await render(false,changed,saved);await input(el,'Measured operating hours','121');await click(el,'Save measured hours');expect(saved).not.toHaveBeenCalled();expect(el.querySelector('[role="status"]')).toBeNull();await act(async()=>resolve());expect(saved).toHaveBeenCalledOnce();expect(changed).not.toHaveBeenCalled();expect(el.textContent).toContain('Measured hours saved.');});
it.each([['Baseline hours','60'],['Baseline date','2026-07-01'],['Rule title','Pump check'],['Rule interval hours','125'],['Rule interval months','8'],['Rule source','Manual revised']])('requires fresh confirmation after editing %s of an already verified rule',async(label,value)=>{const changed=vi.fn();const el=await render(true,changed);await click(el,'Edit Pump service rule');const check=el.querySelector('input[type="checkbox"]') as HTMLInputElement;expect(check.checked).toBe(true);await input(el,label,value);expect(check.checked).toBe(false);await act(async()=>check.click());await click(el,'Save verified rule');expect(changed.mock.calls[0][0].maintenanceRules[0].confirmed).toBe(true);});
it.each(['invalid hours','rule editor','service editor'])('removes earlier success feedback when starting %s',async action=>{const el=await render();await input(el,'Measured operating hours','121');await click(el,'Save measured hours');expect(el.querySelector('[role="status"]')?.textContent).toContain('Measured hours saved');if(action==='invalid hours'){await input(el,'Measured operating hours','120');await click(el,'Save measured hours');expect(el.querySelector('[role="alert"]')?.textContent).toContain('previous');}else await click(el,action==='rule editor'?'Edit Pump service rule':'Record completed service');expect(el.querySelector('[role="status"]')).toBeNull();});
it('records a calendar-only service without hours and preserves replacement and assignment fields',async()=>{const changed=vi.fn();const fixture:Equipment={...equipment,lifespanEnabled:true,lifespanMode:'usage',carsUsed:400,assignments:[{vehicleId:'v',vehicleNumber:'Truck',quantity:1}],maintenanceRules:[{id:'calendar',title:'Calendar check',intervalMonths:6,confirmed:true,source:'Manual',baselineDate:'2026-06-01'}]};const el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root.render(<EquipmentServicePanel items={[fixture]} demo actor={{id:'boss',name:'Manager'}} onSampleChange={changed}/>));await click(el,'Record completed service');await click(el,'Save completed service');expect(changed.mock.calls[0][0]).toMatchObject({lifespanEnabled:true,lifespanMode:'usage',carsUsed:400,assignments:fixture.assignments,serviceHistory:[{ruleId:'calendar',date:'2026-10-08',hours:undefined}]});Object.values(writes).forEach(x=>expect(x).not.toHaveBeenCalled());});
