import React from 'react';
import {act} from 'react';
import {createRoot} from 'react-dom/client';
import {expect,it} from 'vitest';
import MaintenanceActions from './MaintenanceActions';
import type {Vehicle} from '@/types';
it('keeps due work before incomplete setup and exposes field-specific actions',async()=>{const el=document.createElement('div');document.body.append(el);const root=createRoot(el);const v:Vehicle={id:'v',vehicleNumber:'Truck',name:'Truck',licensePlate:'',qrCodeToken:'',status:'active'};try{await act(async()=>root.render(<MaintenanceActions rows={[{vehicle:v,forecasts:[{ruleId:'filters',title:'Filters',status:'needs_setup',source:'',reason:'Baseline missing',missing:['Record current measured mileage.','Add the verified schedule source.'],basis:[]},{ruleId:'oil',title:'Oil',status:'overdue',source:'Manual',reason:'Calendar limit',missing:[],basis:[]}]}]} onEdit={()=>{}}/>));expect(el.textContent!.indexOf('Oil')).toBeLessThan(el.textContent!.indexOf('Filters'));expect(el.textContent).toContain('Measure mileage');expect(el.textContent).toContain('Verify rule source');}finally{await act(async()=>root.unmount());el.remove();}});
it('routes independent baseline setup to the selected rule instead of the oil baseline step',async()=>{const el=document.createElement('div');document.body.append(el);const root=createRoot(el);const v:Vehicle={id:'v',vehicleNumber:'Truck',name:'Truck',licensePlate:'',qrCodeToken:'',status:'active'};let action:unknown[]=[];try{await act(async()=>root.render(<MaintenanceActions rows={[{vehicle:v,forecasts:[{ruleId:'cabin',title:'Cabin filter',status:'needs_setup',source:'Manual',reason:'Missing baseline',missing:['Record Cabin filter completed-service baseline date.'],basis:[]}]}]} onEdit={(...args)=>{action=args;}}/>));const button=Array.from(el.querySelectorAll('button')).find(b=>b.textContent?.includes('Verify service baseline'))!;await act(async()=>button.click());expect(action).toEqual(['v','profile','cabin',3]);}finally{await act(async()=>root.unmount());el.remove();}});
it('separates unknown history from the independent baseline controls',async()=>{const el=document.createElement('div');document.body.append(el);const root=createRoot(el);const v:Vehicle={id:'v',vehicleNumber:'Truck',name:'Truck',licensePlate:'',qrCodeToken:'',status:'active',maintenance:{baselineUnknown:true}};const actions:unknown[][]=[];try{await act(async()=>root.render(<MaintenanceActions rows={[{vehicle:v,forecasts:[{ruleId:'cabin',title:'Cabin filter',status:'needs_setup',source:'Manual',reason:'History unknown',missing:['Verify Cabin filter history or record an explicit completed-service baseline; prior service is unknown.','Record Cabin filter completed-service baseline date.'],basis:[]}]}]} onEdit={(...args)=>{actions.push(args);}}/>));const history=Array.from(el.querySelectorAll('button')).find(b=>b.textContent?.includes('Verify service history'));expect(history).toBeDefined();await act(async()=>history!.click());const baseline=Array.from(el.querySelectorAll('button')).find(b=>b.textContent?.includes('Verify service baseline'))!;await act(async()=>baseline.click());expect(actions).toEqual([['v','profile','cabin',2],['v','profile','cabin',3]]);}finally{await act(async()=>root.unmount());el.remove();}});
