import React from 'react';
import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import VehicleMaintenanceForm from './VehicleMaintenanceForm';
import type { Vehicle } from '@/types';
const vehicle: Vehicle={id:'v',vehicleNumber:'Truck',name:'Maverick',licensePlate:'',qrCodeToken:'',status:'active',odometer:1000};
let root: ReturnType<typeof createRoot>;
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-10-08T12:00:00Z'));});
afterEach(async()=>{if(root) await act(async()=>root.unmount());document.body.innerHTML='';vi.useRealTimers();});
async function render(mode: any='profile',onSave=vi.fn().mockResolvedValue(undefined),props:Partial<React.ComponentProps<typeof VehicleMaintenanceForm>>={}){const el=document.createElement('div');document.body.append(el);root=createRoot(el);await act(async()=>root.render(<VehicleMaintenanceForm vehicle={vehicle} mode={mode} actor="Manager" demo onClose={()=>{}} onSave={onSave} {...props}/>));return el;}
async function click(el:HTMLElement,text:string){const b=Array.from(el.querySelectorAll('button')).find(b=>b.textContent?.includes(text));expect(b).toBeDefined();await act(async()=>b!.click());}
async function check(el:HTMLElement,label:string){const l=Array.from(el.querySelectorAll('label')).find(l=>l.textContent?.includes(label));expect(l).toBeDefined();await act(async()=>l!.querySelector('input')!.click());}
it('navigates three accessible steps and saves an honest partial unknown-history draft',async()=>{const save=vi.fn().mockResolvedValue(undefined);const el=await render('profile',save);expect(el.textContent).toContain('Step 1 of 3');await click(el,'Next');expect(el.textContent).toContain('Step 2 of 3');await check(el,'Service history is unknown');await click(el,'Next');expect(el.textContent).toContain('Step 3 of 3');await click(el,'Save draft');expect(save.mock.calls[0][1].profile.baselineUnknown).toBe(true);expect(save.mock.calls[0][1].service).toBeUndefined();expect(el.textContent).toContain('Oil interval');});
it('requires explicit measured mileage confirmation and invalidates it on edit',async()=>{const save=vi.fn();const el=await render('reading',save);await click(el,'Save sample change');expect(save).not.toHaveBeenCalled();expect(el.textContent).toContain('Confirm that this mileage was measured');await check(el,'I measured');await input(el,'Current odometer','1001');await click(el,'Save sample change');expect(save).not.toHaveBeenCalled();await check(el,'I measured');await click(el,'Save sample change');expect(save.mock.calls[0][1].confirmed).toBe(true);});
it('retains a failed save and displays the error without closing',async()=>{const el=await render('reading',vi.fn().mockRejectedValue(new Error('Connection failed')));await check(el,'I measured');await click(el,'Save sample change');expect(el.querySelector('[role="alert"]')?.textContent).toContain('Connection failed');expect(el.querySelector('[role="dialog"]')).not.toBeNull();});
it('blocks correction without a reason and retains audit lineage when saving',async()=>{const save=vi.fn().mockResolvedValue(undefined);const el=await render('correction',save);await click(el,'Save sample change');expect(save).not.toHaveBeenCalled();expect(el.textContent).toContain('Enter the correction reason');});
it('does not let a booked appointment imply completed service',async()=>{const save=vi.fn().mockResolvedValue(undefined);const el=await render('appointment',save);const select=Array.from(el.querySelectorAll('select')).find(s=>s.parentElement?.textContent?.includes('Appointment status'))!;await act(async()=>{const setter=Object.getOwnPropertyDescriptor(HTMLSelectElement.prototype,'value')!.set!;setter.call(select,'completed');select.dispatchEvent(new Event('change',{bubbles:true}));});await click(el,'Save sample change');expect(save).not.toHaveBeenCalled();expect(el.textContent).toContain('Link a recorded completed service');});

async function input(el:HTMLElement,label:string,value:string){const field=Array.from(el.querySelectorAll('label')).find(l=>l.textContent?.includes(label))!.querySelector('input')!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(field,value);field.dispatchEvent(new Event('input',{bubbles:true}));});}
it('appends correction payload with reason, original id, actor and timestamp',async()=>{const save=vi.fn().mockResolvedValue(undefined);const original={id:'original',kind:'filters' as const,ruleId:'cabin',title:'Cabin filter',date:'2026-10-01',odometer:900,recordedBy:'first-manager'};const el=await render('correction',save,{original,actor:'manager-id',vehicle:{...vehicle,maintenance:{rules:[{id:'cabin',title:'Cabin filter',kind:'filters',intervalMiles:20000,source:'Manual',confirmed:true,recurrence:'after_service'}]}}});await input(el,'Correction reason','Receipt corrected mileage');await click(el,'Save sample change');expect(save.mock.calls[0][1]).toMatchObject({supersedesId:'original',correctionReason:'Receipt corrected mileage',ruleId:'cabin',recordedBy:'manager-id'});expect(save.mock.calls[0][1].recordedAt).toBe('2026-10-08T12:00:00.000Z');expect(save.mock.calls[0][1].id).not.toBe('original');});
it('offers year-specific normal Ford oil limits only as an unconfirmed review draft',async()=>{const save=vi.fn().mockResolvedValue(undefined);const el=await render('profile',save,{initialStep:3,vehicle:{...vehicle,maintenance:{make:'Ford',model:'Maverick',year:2022,operatingProfile:'Normal use'}}});await click(el,'Review 2022 Maverick normal oil draft');await click(el,'Save sample change');expect(save.mock.calls[0][1].profile).toMatchObject({oilIntervalMiles:10000,oilIntervalMonths:12,scheduleConfirmed:false});expect(save.mock.calls[0][1].profile.scheduleSource).toContain('G2213641');});
it('does not offer normal Ford presets to towing or dusty profiles',async()=>{const el=await render('profile',undefined,{initialStep:3,vehicle:{...vehicle,maintenance:{make:'Ford',model:'Maverick',year:2023,operatingProfile:'Towing / heavy loads'}}});expect(el.textContent).not.toContain('Review 2023 Maverick normal oil draft');});
it('initializes direct actions with the independent service rule and category',async()=>{const save=vi.fn().mockResolvedValue(undefined);const el=await render('service',save,{initialRuleId:'cabin',vehicle:{...vehicle,maintenance:{rules:[{id:'cabin',title:'Cabin filter',kind:'filters',intervalMiles:20000,source:'Manual',confirmed:true,recurrence:'after_service'}]}}});await click(el,'Save sample change');expect(save.mock.calls[0][1]).toMatchObject({kind:'filters',title:'Cabin filter',ruleId:'cabin'});});
it('identifies and focuses an independently selected rule during profile setup',async()=>{const el=await render('profile',undefined,{initialRuleId:'cabin',initialStep:3,vehicle:{...vehicle,maintenance:{rules:[{id:'cabin',title:'Cabin filter',kind:'filters',intervalMiles:20000,source:'Manual',confirmed:false,recurrence:'after_service'},{id:'brakes',title:'Brake fluid',kind:'other',intervalMonths:36,source:'Manual',confirmed:false,recurrence:'after_service'}]}}});const selected=el.querySelector('[data-maintenance-rule="cabin"]');expect(selected).not.toBeNull();expect(selected?.getAttribute('data-selected-rule')).toBe('true');expect(selected?.textContent).toContain('Selected rule');expect(document.activeElement).toBe(selected);});
it.each(['tires','filters','other'] as const)('preserves legacy %s correction lineage without adding an oil rule id',async(kind)=>{const save=vi.fn().mockResolvedValue(undefined);const original={id:`original-${kind}`,kind,title:`Legacy ${kind}`,date:'2026-10-01',odometer:900,recordedBy:'first-manager'};const el=await render('correction',save,{original});expect(el.querySelector('select')?.value).toBe(kind);await input(el,'Correction reason','Receipt adjustment');await click(el,'Save sample change');expect(save.mock.calls[0][1]).toMatchObject({kind,supersedesId:original.id});expect(save.mock.calls[0][1].ruleId).toBeUndefined();});
it.each(['tires','filters','other'] as const)('initializes a legacy %s timeline action as that service category',async(kind)=>{const save=vi.fn().mockResolvedValue(undefined);const el=await render('service',save,{initialRuleId:kind});await click(el,'Save sample change');expect(save.mock.calls[0][1].kind).toBe(kind);expect(save.mock.calls[0][1].title).not.toContain('Oil');expect(save.mock.calls[0][1].ruleId).toBeUndefined();});
